# Generated by Django 4.0 on 2022-02-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.CharField(max_length=500, unique=True)),
                ('movie_details', models.JSONField()),
                ('watched', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
